### ISSUE TITLE
Experimental syntax parsing error

### ISSUE THREAD

**Issue by WarrenWongCodes** [BlueOcean37/Bravo#1]
- Babel configuration needs to account for JSX, eslint error.
- Possible plugin needed

**Comment by lerisse** [comment]
I pulled the repo and not getting any errors. Possibly this has to do with your local environment setup @WarrenWongCodes ?

**Comment by WarrenWongCodes** [comment]
This issue still exists on multiple local environments.

**Comment by lerisse** [comment]
I spend too much time debugging this last night. I'll open up a help desk ticket to hopefully get it fixed today.

**Comment by WarrenWongCodes** [comment]
If you think its worth the time, sure.

**Comment by lerisse** [comment]
eslintrc.json
removed parser parameter. This was hiding our styling rules so new errors will most likely appear.

**Comment by WarrenWongCodes** [comment]
This solved the issue ? @lerisse
