### ISSUE TITLE
Airbnb Linting Errors

### ISSUE THREAD

**Issue by WarrenWongCodes** [BlueOcean37/Bravo#50]
Airbnb linting was never working, there was an extra line of code that blocked it. See below on the fix.

- Remove line 15 eslintrc file 
`"parser": "@babel/eslint-parser"`

- After removing line 15, go through your own files and clean up the errors best you can.

**Comment by lerisse** [comment]
Done refactoring header component

**Comment by WarrenWongCodes** [comment]
Authentication components refactored.
