### ISSUE TITLE
Search Bar - type error

### ISSUE THREAD

**Issue by WarrenWongCodes** [BlueOcean37/Bravo#94]
Error message: Cannot read property 'toLowerCase' of undefined

When attempting a search.
Make sure to double check the endpoint!

**Comment by lerisse** [comment]
Hey, @WarrenWongCodes I tested with Andrew and Diego yesterday and they are not getting this error. Can you make sure to restart the server and delete your bundle.js file, rerun Webpack and get back to me if the error still occurs.

**Comment by WarrenWongCodes** [comment]
<img width="809" alt="Screen Shot 2021-07-18 at 12 56 59 PM" src="https://user-images.githubusercontent.com/8570718/126075728-613026eb-971e-4eeb-b31a-8b02e2ae5c53.png">

Still having that issue when attempting to go in the search bar. Not sure, maybe its a issue from my end? This is the error message I recieve. @lerisse

**Comment by WarrenWongCodes** [comment]
Closing issue. Seemed like a problem on my end.
